package tech.project.schedule.model.enums;

public enum NotificationStatus {
    PROJECT_MEMBER_ADDED,
    TASK_ASSIGNEE_ADDED,
    TASK_UPDATED,
    TASK_COMPLETED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    TASK_DELETED,
    TASK_COMMENT_ADDED,
    TASK_COMMENT_DELETED,
    TASK_COMMENT_UPDATED,
    TASK_DEPENDENCY_ADDED,
    TASK_DEPENDENCY_DELETED,
    TASK_DEPENDENCY_UPDATED,
    TASK_FILE_UPLOADED,
    TASK_FILE_DELETED,
    TASK_FILE_UPDATED
}