spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: CLIENT_ID                #DODAĆ ODPOWIEDNIE
            client-secret: CLIENT_SECRET
            scope:
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
